# Evaluate with different metrics

In [20]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [21]:
from collections import defaultdict
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, brier_score_loss
import pickle

import sys
sys.path.append("..")
sys.path.append("../prediction_src")

from fit_prediction_model import *
from evaluate_prediction_model import *
from params import *

In [25]:
with open("../models/DAG_model_youden_mens.pkl","rb") as f:
    youden_mens_data_dict = pickle.load(f)

In [26]:
with open("../models/DAG_model_youden_mens_pred.pkl","rb") as f:
    youden_mens_pred_dict = pickle.load(f)

In [ ]:
with open("../models//DAG_model_youden_final.pkl","rb") as f:
    youden_basis_model_dict = pickle.load(f)

In [28]:
with open("../models/DAG_model_dyspareunie.pkl","rb") as f:
    dyspareunie_model_dict = pickle.load(f)

In [29]:
with open("../models/DAG_model_urinieren.pkl","rb") as f:
    urinieren_model_dict = pickle.load(f)

In [30]:
with open("../models/menstruationsschmerz_predictor.pkl","rb") as f:
    menstruationsschmerz_dict = pickle.load(f)

In [31]:
with open("../models/mens_data_model.pkl","rb") as f:
   mens_data_dict = pickle.load(f)

In [33]:
with open("../models/DAG_model_durchfall.pkl","rb") as f:
    basis_model_dict= pickle.load(f)

In [34]:
with open("../models/DAG_model_nvf.pkl","rb") as f:
    nvf_model_dict = pickle.load(f)

In [35]:
with open("../models/DAG_model_thresh_new.pkl","rb") as f:
    model_dict = pickle.load(f)

In [36]:
mens_pred_dict[list(mens_pred_dict.keys())[0]]["model_name"]=get_df_name(mens_pred_dict)

In [37]:
mens_dict[list(mens_dict.keys())[0]]["model_name"]=get_df_name(mens_dict)

In [38]:
basis_model_dict[list(basis_model_dict.keys())[0]]["model_name"]=get_df_name(basis_model_dict)

In [39]:
model_dict[list(model_dict.keys())[0]]["model_name"]=get_df_name(model_dict)

In [14]:
nvf_model_dict[list(nvf_model_dict.keys())[0]]["model_name"]=get_df_name(nvf_model_dict)

In [15]:
urinieren_model_dict[list(urinieren_model_dict.keys())[0]]["model_name"]=get_df_name(urinieren_model_dict)

In [16]:
dyspareunie_model_dict[list(dyspareunie_model_dict.keys())[0]]["model_name"]=get_df_name(dyspareunie_model_dict)

In [40]:
mens_metrics_of_interest = calc_eval_metrics(mens_data_dict,MET_LIST)
mens_pred_metrics_of_interest = calc_eval_metrics(menstruationsschmerz_dict,MET_LIST)
basis_metrics_of_interest = calc_eval_metrics(basis_model_dict,MET_LIST)

In [46]:
full_metrics_of_interest = calc_eval_metrics(model_dict,MET_LIST)

In [18]:
nvf_metrics_of_interest = calc_eval_metrics(nvf_model_dict,MET_LIST)
dyspareunie_metrics_of_interest = calc_eval_metrics(dyspareunie_model_dict,MET_LIST)
urinieren_metrics_of_interest = calc_eval_metrics(urinieren_model_dict,MET_LIST)

In [44]:
mens_pred_metrics_of_interest.reset_index(inplace=True)
mens_pred_metrics_of_interest["Model"]="Menstruationsschmerz Prädiktor"

In [48]:
full_metrics_of_interest.reset_index(inplace=True)
full_metrics_of_interest["Model"]="Alle DAG-Prädiktoren"

In [49]:
basis_metrics_of_interest.reset_index(inplace=True)
basis_metrics_of_interest["Model"]="DAG-Prädiktoren ohne Durchfall"

In [51]:
all_metrics_of_interest = pd.concat([basis_metrics_of_interest,mens_metrics_of_interest,mens_pred_metrics_of_interest,full_metrics_of_interest])
all_metrics_of_interest

,Model,AUC,Brier Score Loss,Calibration Intercept,Calibration Slope
0,DAG-Prädiktoren ohne Durchfall,0.66,0.02,0.26,1.07
endo_data_as_groupedTrue_is_sumFalse_nvfFalse,NaN,0.60,0.05,-0.12,0.96
0,Menstruationsschmerz Prädiktor,0.60,0.02,0.51,1.14
0,Alle DAG-Prädiktoren,0.66,0.02,0.27,1.08

In [52]:
from calibration import classification_metrics

In [53]:
classification_metrics(mens_data_dict,mens_data_dict[list(mens_data_dict.keys())[0]]["model"].threshold)

   Sensitivity  Specificity  PPV  FPR  TPR  Accuracy  TP  FP   FN    TN
0          0.0          1.0  NaN  0.0  0.0  0.951488   0   0  119  2334

In [ ]:
classification_metrics(mens_data_dict,mens_data_dict[list(mens_data_dict.keys())[0]]["model"].threshold)

In [19]:
all_metrics_of_interest = pd.concat([basis_metrics_of_interest,mens_pred_metrics_of_interest,mens_metrics_of_interest,nvf_metrics_of_interest,dyspareunie_metrics_of_interest,urinieren_metrics_of_interest])
all_metrics_of_interest

,AUC,Brier Score Loss,Calibration Intercept,Calibration Slope
Model,,,,
durchfall_model_dict,0.66,0.02,0.26,1.07
mens_pred_dict,0.75,0.02,0.10,1.04
mens_dict,0.60,0.05,-0.12,0.96
nvf_model_dict,0.67,0.02,0.12,1.04
dyspareunie_model_dict,0.66,0.02,0.25,1.07
urinieren_model_dict,0.65,0.02,0.36,1.10

In [47]:
basis_model_dict[list(basis_model_dict.keys())[0]]["model"].coef_

Verdauungsstörungen       0.378372
Blutung                   0.476036
Dyspareunie               0.361333
Menstruationsschmerzen    0.809046
Bauchschmerzen            0.818461
Urinieren                 0.813285
Verstopfung              -0.111543
dtype: float64

# Vorhersagewerte für Testset

In [20]:
basis_model_dict[list(basis_model_dict.keys())[0]]["model"].threshold

0.02281541491972887

In [17]:
basis_model_dict[list(basis_model_dict.keys())[0]]["prob_1_test"].mean()

0.021412536323855882

In [21]:
basis_model_dict[list(basis_model_dict.keys())[0]]["pred_test"].mean()

0.2648943626714729

In [22]:
X_test_true = basis_model_dict[list(basis_model_dict.keys())[0]]["X_test_true"]

In [23]:
Mens_test_true = X_test_true[X_test_true["Menstruationsschmerzen"]==1].copy()

In [24]:
X_test_true.shape, Mens_test_true.shape

((19974, 8), (4675, 8))

In [25]:
basis_model_dict[list(basis_model_dict.keys())[0]]["model"].predict(X_test_true).mean().round(3)

0.265

In [26]:
basis_model_dict[list(basis_model_dict.keys())[0]]["model"].predict(Mens_test_true).mean()

0.9997860962566845

In [27]:
pd.Series(basis_model_dict[list(basis_model_dict.keys())[0]]["model"].predict_proba(X_test_true)[:,1]).mean().round(3)

0.021

In [29]:
pd.Series(basis_model_dict[list(basis_model_dict.keys())[0]]["model"].predict_proba(Mens_test_true)[:,1]).mean().round(3)

0.065

In [28]:
basis_model_dict[list(basis_model_dict.keys())[0]]["model"].threshold.round(3)

0.023